[CREATE] src/- create a filter employees by job / [FIX] src/ - filter …
PG-HENRY-13/PG-Escuelas pull request #40
Opened 2022-05-04 17:06 UTC by JoaquinNogueira

2022-05-05 04:32 UTC, moronifacundo requested changes

2022-05-05 04:32 UTC, moronifacundo commented on src/redux/actions/index.ts
> +    const response = await axios.get<any>("http://localhost:3001/api/job/"); ///CAMBIAR EL ANY
Joaco, aca fijate de usar el url q viene por variable para no generar problemas al hacer el deploy

2022-05-05 04:32 UTC, moronifacundo commented on src/redux/actions/index.ts
> +      "http://localhost:3001/api/filterjobs?JobId=" + JobId,
lo mismo aca, mejor usar variables de links

2022-05-06 13:23 UTC, SantiagoMontion approved these changes

2022-05-06 13:23 UTC, merged